//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :2.0.50727.8689
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfWebService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Option", Namespace="http://schemas.datacontract.org/2004/07/WcfWebService")]
    public partial class Option : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private WcfWebService.Price CallPriceField;
        
        private WcfWebService.ErrorType ErrorField;
        
        private double MaturityField;
        
        private int NbrOfSimulationsField;
        
        private WcfWebService.Price PutPriceField;
        
        private double RiskFreeInterestRateField;
        
        private double StrikeField;
        
        private double UnderlyingPriceField;
        
        private double VolatilityField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfWebService.Price CallPrice
        {
            get
            {
                return this.CallPriceField;
            }
            set
            {
                this.CallPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfWebService.ErrorType Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Maturity
        {
            get
            {
                return this.MaturityField;
            }
            set
            {
                this.MaturityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NbrOfSimulations
        {
            get
            {
                return this.NbrOfSimulationsField;
            }
            set
            {
                this.NbrOfSimulationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WcfWebService.Price PutPrice
        {
            get
            {
                return this.PutPriceField;
            }
            set
            {
                this.PutPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double RiskFreeInterestRate
        {
            get
            {
                return this.RiskFreeInterestRateField;
            }
            set
            {
                this.RiskFreeInterestRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Strike
        {
            get
            {
                return this.StrikeField;
            }
            set
            {
                this.StrikeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double UnderlyingPrice
        {
            get
            {
                return this.UnderlyingPriceField;
            }
            set
            {
                this.UnderlyingPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Volatility
        {
            get
            {
                return this.VolatilityField;
            }
            set
            {
                this.VolatilityField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Price", Namespace="http://schemas.datacontract.org/2004/07/WcfWebService")]
    public partial class Price : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<double> BSField;
        
        private System.Nullable<double> MCField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> BS
        {
            get
            {
                return this.BSField;
            }
            set
            {
                this.BSField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MC
        {
            get
            {
                return this.MCField;
            }
            set
            {
                this.MCField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorType", Namespace="http://schemas.datacontract.org/2004/07/WcfWebService")]
    public partial class ErrorType : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<double> CallField;
        
        private System.Nullable<double> PutField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Call
        {
            get
            {
                return this.CallField;
            }
            set
            {
                this.CallField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Put
        {
            get
            {
                return this.PutField;
            }
            set
            {
                this.PutField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IService")]
public interface IService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetNewOption", ReplyAction="http://tempuri.org/IService/GetNewOptionResponse")]
    WcfWebService.Option GetNewOption();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IServiceChannel : IService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ServiceClient : System.ServiceModel.ClientBase<IService>, IService
{
    
    public ServiceClient()
    {
    }
    
    public ServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WcfWebService.Option GetNewOption()
    {
        return base.Channel.GetNewOption();
    }
}
